CREATE TABLE [dbo].[User]
(
	[ID] INT NOT NULL IDENTITY,
	[EMAIL] NVARCHAR(100) NOT NULL UNIQUE,
	[FIRSTNAME] NVARCHAR(100) NOT NULL,
	[LASTNAME] NVARCHAR(100) NOT NULL,
	[BORNDATE] DATETIME NULL,
	[PROFILEPICTURE] IMAGE NULL,
	[PASSWORD] VARCHAR(100) NOT NULL,
    CONSTRAINT [pk_user] PRIMARY KEY ([ID]) 
)
